### PR TITLE
Modrewrite

### PR DESCRIPTION
**Pull request by FlashHit**
- Simplified alot of code. Rewrote the whole mod. Restructured everything.
- Added rcon commands:
  - Allows you to enable/disable the mod (forceEnable to enable the mod immediately (but this will lag the game for a few seconds):
  - `pixels.enabled <boolean: enable> <boolean?: forceEnable>`
  - Allows you to enable/disable specific options
  - `pixels.updateOption <string: option> <boolean: enable>`
  - Allows you to enable specific options live
  - `pixels.enableOptionLive <string: option>`
  - Returns a list with all options:
  - `pixels.getOptionsList`
  - Returns a list with all enabled options:
  - `pixels.getEnabledOptions`
- Support `modList.reloadExtensions`. You can modify the files and then test the changes (but this will lag the game for a few seconds as well).
- Leftovers:
  - Categories are still missing. Right now there are too many options. So with categories it should be easier to enable/disable stuff.
  - MapMode is gone rn. Couldn't think of a good way to add support for it rn.
  - Removed the EBXUtils. IMO this should be loaded seperately from this mod.
  - Might try to fix the lags when using `pixels.enabled true true` or `modList.reloadExtensions`

Anyways have fun.

### CODE REVIEW

**Comment by FlashHit** [comment]
Here a small example of the `modList.reloadExtensions`-support feature.
It changed the ammo for the M16A3.

https://user-images.githubusercontent.com/56718716/206820936-b9c836c2-b9b9-42b1-992f-0a9cfa412c9c.mp4

**Comment by spatieman** [comment]
`hmm...

[VeniceEXT] [vu-pixelsmod-main] Error: [string "__init__.lua"]:58: attempt to call a nil value (method 'RegisterPartitionLoadHandlerOnce')
stack traceback:


but what about security ?
it is not the idea avery player can tweak stuff, hehe.

**Comment by FlashHit** [comment]
`updateBranch dev` seems to be required. Once `Build 19968` gets pushed to prod it should work as usuell again.

**Comment by spatieman** [comment]
tought i had some bug stuff, my my client was PROD version , and that gave some weard isues
after updateing the client to DEV, all seems to work, wel, the !modreload does nothing, cant find it in any of the lua scripts also.

**Comment by FlashHit** [comment]
`!modreload` requires this procon plugin: https://discord.com/channels/125257766649593856/721729208832884747/825422834355798026

**Comment by spatieman** [comment]
ah, ,installed, and works.
get slowly the idea of the coding,, 
the real challange if i get to tweak the gunmaster mod
the way how the ammo is moddified is difrent

**Pull request merged**
